"use strict";
exports.__esModule = true;
var bbdd_1 = require("./bbdd");
var movie_1 = require("./movie");
var imdb_1 = require("./imdb");
var persona = new bbdd_1.Professional("Leonardo", 45, "hombre", 70, 175, "rubio", "verde", "britanico", false, "britanico", 1, "actor");
var x = require('readline-sync');
var title = x.question("Titulo Pelicula: ");
var releaseYear = x.question("Año Estreno: ");
var actors = [persona];
var nationality = x.question("Nacionalidad: ");
var director = x.question("Director: ");
var writer = x.question("Escritor: ");
var language = x.question("Idioma: ");
var plataform = x.question("Plataforma: ");
var isMCU = x.question("¿Es del universo ISMCU?: ");
var mainChararcterName = x.question("Personaje Principal: ");
var producer = x.question("Productor: ");
var distributor = x.question("Distribuidor: ");
var genre = x.question("Genero: ");
var pelicula = new movie_1.Movie(title, releaseYear, nationality, genre);
pelicula.actors = actors;
pelicula.director = director;
pelicula.writer = writer;
pelicula.language = language;
pelicula.plataform = plataform;
pelicula.isMCU = isMCU;
pelicula.mainChararcterName = mainChararcterName;
pelicula.producer = producer;
pelicula.distributor = distributor;
pelicula.genre = genre;
var datosImdb = new imdb_1.Imdb([]);
datosImdb = datosImdb.obtenerInstanciaIMDB("imdbBBDD.json");
datosImdb.peliculas.push(pelicula);
datosImdb.escribirFicheroJSON("imdbBBDD.json");
