"use strict";
exports.__esModule = true;
var bbdd_1 = require("./bbdd");
var person = new bbdd_1.Professional("Leonardo", 45, "hombre", 70, 175, "rubio", "verde", "britanico", false, "britanico", 1, "actor");
var person1 = new bbdd_1.Professional("Penelope", 50, "mujer", 56, 175, "morena", "marrones", "española", false, "española", 4, "actriz");
var person2 = new bbdd_1.Professional("Juan", 25, "hombre", 70, 190, "rubio", "verde", "español", false, "español", 0, "actor");
var person3 = new bbdd_1.Professional("Sofia", 55, "mujer", 56, 180, "morena", "marrones", "mexicana", false, "mexicana", 0, "actriz");
console.log(person.printAll());
console.log(person1.printAll());
console.log(person2.printAll());
console.log(person3.printAll());
